### ISSUE TITLE
Order of events changes scoring

### ISSUE THREAD

**Issue by brian-romanowski-nuance** [Lybarger/brat_scoring#3]
Happened to notice the following, that the order of events in the .ann files affect the scoring result.  For example:

    mkdir foo
    cp /path/to/train/mimic/1712.txt foo
    sort /path/to/train/mimic/1712.ann > foo/1712.ann
    
    mkdir bar
    cp /path/to/train/mimic/1712.txt bar
    sort -r /path/to/train/mimic/1712.ann > bar/1712.ann  # same file, different order of annotations
    
    python brat_scoring/brat_scoring/run_sdoh_scoring.py foo bar foobar.csv --score_trig overlap --score_span exact --score_labeled label --include_detailed

Gives, in `foobar.csv`:

    event,argument,subtype,NT,NP,TP,P,R,F1
    OVERALL,OVERALL,OVERALL,24,24,19,0.7916666666666666,0.7916666666666666,0.7916666666666666
    Alcohol,Amount,N/A,1,1,0,0.0,0.0,0.0
    Alcohol,Frequency,N/A,1,1,0,0.0,0.0,0.0
    Alcohol,StatusTime,current,1,1,0,0.0,0.0,0.0
    Alcohol,StatusTime,past,1,1,0,0.0,0.0,0.0
    Alcohol,Trigger,N/A,2,2,2,1.0,1.0,1.0
    Alcohol,Type,N/A,1,1,0,0.0,0.0,0.0
    Drug,History,N/A,1,1,1,1.0,1.0,1.0
    Drug,StatusTime,current,1,1,1,1.0,1.0,1.0
    Drug,StatusTime,past,1,1,1,1.0,1.0,1.0
    Drug,Trigger,N/A,2,2,2,1.0,1.0,1.0
    Drug,Type,N/A,3,3,3,1.0,1.0,1.0
    LivingStatus,StatusTime,current,1,1,1,1.0,1.0,1.0
    LivingStatus,Trigger,N/A,1,1,1,1.0,1.0,1.0
    LivingStatus,TypeLiving,with_others,1,1,1,1.0,1.0,1.0
    Tobacco,Amount,N/A,1,1,1,1.0,1.0,1.0
    Tobacco,Duration,N/A,1,1,1,1.0,1.0,1.0
    Tobacco,Frequency,N/A,1,1,1,1.0,1.0,1.0
    Tobacco,StatusTime,current,1,1,1,1.0,1.0,1.0
    Tobacco,Trigger,N/A,1,1,1,1.0,1.0,1.0
    Tobacco,Type,N/A,1,1,1,1.0,1.0,1.0

Where there are two "Alcohol" events with the same Alcohol trigger and different arguments.  It looks like the scoring script must compare one event to the other, effectively, based on the order in which they appear in the .ann files?

**Comment by Lybarger** [comment]
Brian,

The script intentionally only allows each gold or predicted trigger to be matched one time. For example, if there is one gold trigger associated with a span and there are two predicted triggers associated with the same span, only one of the predicted triggers can match. If there are multiple predicted triggers with the same span, then the order in the ann file will impact performance.

There are a very small number of gold events with identical triggers in the annotated corpus, relative to the total number of events. In creating an extraction architecture and decoding the predictions, I suggest avoiding the creation of events with duplicate triggers.

Best regards,

Kevin

From: Brian Romanowski ***@***.***>
Sent: Tuesday, May 3, 2022 3:33 PM
To: Lybarger/brat_scoring ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Lybarger/brat_scoring] Order of events changes scoring (Issue #3)


Happened to notice the following, that the order of events in the .ann files affect the scoring result. For example:

mkdir foo

cp /path/to/train/mimic/1712.txt foo

sort /path/to/train/mimic/1712.ann > foo/1712.ann



mkdir bar

cp /path/to/train/mimic/1712.txt bar

sort -r /path/to/train/mimic/1712.ann > bar/1712.ann



python brat_scoring/brat_scoring/run_sdoh_scoring.py foo bar foobar.csv --score_trig overlap --score_span exact --score_labeled label --include_detailed

Gives, in foobar.csv:

event,argument,subtype,NT,NP,TP,P,R,F1

OVERALL,OVERALL,OVERALL,24,24,19,0.7916666666666666,0.7916666666666666,0.7916666666666666

Alcohol,Amount,N/A,1,1,0,0.0,0.0,0.0

Alcohol,Frequency,N/A,1,1,0,0.0,0.0,0.0

Alcohol,StatusTime,current,1,1,0,0.0,0.0,0.0

Alcohol,StatusTime,past,1,1,0,0.0,0.0,0.0

Alcohol,Trigger,N/A,2,2,2,1.0,1.0,1.0

Alcohol,Type,N/A,1,1,0,0.0,0.0,0.0

Drug,History,N/A,1,1,1,1.0,1.0,1.0

Drug,StatusTime,current,1,1,1,1.0,1.0,1.0

Drug,StatusTime,past,1,1,1,1.0,1.0,1.0

Drug,Trigger,N/A,2,2,2,1.0,1.0,1.0

Drug,Type,N/A,3,3,3,1.0,1.0,1.0

LivingStatus,StatusTime,current,1,1,1,1.0,1.0,1.0

LivingStatus,Trigger,N/A,1,1,1,1.0,1.0,1.0

LivingStatus,TypeLiving,with_others,1,1,1,1.0,1.0,1.0

Tobacco,Amount,N/A,1,1,1,1.0,1.0,1.0

Tobacco,Duration,N/A,1,1,1,1.0,1.0,1.0

Tobacco,Frequency,N/A,1,1,1,1.0,1.0,1.0

Tobacco,StatusTime,current,1,1,1,1.0,1.0,1.0

Tobacco,Trigger,N/A,1,1,1,1.0,1.0,1.0

Tobacco,Type,N/A,1,1,1,1.0,1.0,1.0

Where there are two "Alcohol" events with the same Alcohol trigger and different arguments. It looks like the scoring script must compare one event to the other, effectively, based on the order in which they appear in the .ann files?

**Comment by brian-romanowski-nuance** [comment]
Ok, I'll take this into account.  Thanks!
